-- at will
CREATE TABLE dbamv.fornecedor_mate( CD_FORNEC NUMBER
                                  , DS_FORNEC VARCHAR2(30)
                                  , DT_CRIACAO DATE
                                  , SN_ATIVO VARCHAR2(5)
                                  , TP_FORNEC VARCHAR2(5)
                                  );


INSERT INTO dbamv.fornecedor_mate
(cd_fornec, ds_fornec, dt_criacao, sn_ativo, tp_fornec)
VALUES
(1, 'ADESCOL', TO_DATE('13/06/2023','dd/mm/yyyy'), 'S', 'L') ;


----------------------- UDEMY || PL/SQL ----------------------------

TALUNO

ALTER TABLE TALUNO ADD ESTADO CHAR (2) DEFAULT 'RS';


UPDATE taluno
SET estado = 'AC' , SALARIO = 250
WHERE cod_aluno = 44;


UPDATE taluno
SET estado = 'MA' , SALARIO = 2090
WHERE cod_aluno = 1;


UPDATE taluno
SET estado = 'PE' , SALARIO = 2580
WHERE cod_aluno = 2;

UPDATE taluno
SET estado = 'SP' , SALARIO = 2550
WHERE cod_aluno = 25;

UPDATE taluno
SET estado = 'BH' , SALARIO = 2589
WHERE cod_aluno = 5;

INSERT INTO taluno (cod_aluno, nome, cidade)
VALUES (seq_aluno.NEXTVAL,'valdo' , 'dois irmaos');


SELECT estado, salario, nome FROM taluno  -- order by, desc, serve para colocar em orden descrescente
ORDER BY estado, salario DESC;


ALTER TABLE taluno ADD nascimento DATE DEFAULT SYSDATE - 1000;



SELECT SYSDATE - SYSDATE - 100 FROM DUAL;



UPDATE taluno
SET NASCIMENTO = '17/02/2020'
WHERE cod_aluno = 1;

tcurso



CREATE TABLE  ( CD_CURSO NUMBER (1)
                  , NM_CURSO VARCHAR2
                  , VALOR NUMBER (20)
                  , CARGA_HORARIA NUMBER (20)


-- CAPITULO 4 --

SELECT * FROM TALUNO;

SELECT Concat (COD_ALUNO, NOME) FROM TALUNO; -- CONCAT, SERVE PARA TRAZER DUAS COLUNAS JUNTAS

SELECT NOME, InitCap (NOME)FROM TALUNO;   -- INITCAP,, TRANSFORMA A PRIMEIRA LETRA DAS PALAVRAS EM MAIUSCULA.

SELECT NOME, InStr (NOME, 'R') FROM TALUNO; -- SERVE PARA SABER A POSIÇAO DA LETRA ESCOLHIDA COMO O (R).

SELECT NOME, Length (NOME) FROM TALUNO;  -- CONTA QUANTOS CARACTERES TEM NA COLUNA ESCOLHIDA.

SELECT NOME, Lower (NOME) FROM TALUNO; --  TRANSFORMA A COLUNA PARA MINUSCULO SOMENTE NO SELECT.

SELECT NOME, Upper (NOME) FROM TALUNO; --  TRANSFORMA DO MINUSCULO TUDO PARA MAIUSCULO.

SELECT InitCap ('JOSE DA SILVA') FROM DUAL;

SELECT COD_ALUNO, LPad (COD_ALUNO,5,'0') FROM TALUNO;  -- LEFT = ESQUERDA, quantidades de caracter a esquerda

SELECT NOME, SALARIO, RPad (SALARIO,8,'0') FROM TALUNO; --  quantidades de caracter a direita.

SELECT nome, SubStr (nome, 1, 3) FROM TALUNO; -- COPIA PARTE DE UM CAMPO OU TEXTO, POSIÇAO, QUANTIDADE DE CARACTER

SELECT NOME, SubStr (NOME, 1, 1) FROM TALUNO;

SELECT REPLACE (NOME, 'R', '$') FROM TALUNO; -- SUBATITUI O 'R' POR '$'.



SELECT * FROM TALUNO
WHERE Lower(NOME) = 'marcio';

SELECT * FROM TALUNO
WHERE Upper (NOME) = 'MARCIO';

SELECT * FROM TALUNO
WHERE Upper(SubStr (CIDADE, 1,3)) = 'CAN';

UPDATE TALUNO SET
SALARIO = 633.47
WHERE COD_ALUNO = 1;




------------- DATA-----------

SELECT SYSDATE FROM DUAL; -- SYDATE´RETORNA DATA E HORA DO SERVIDOR.



-- ROUND E TRUNC
SELECT Round (45.925, 2),  -- ARREDONDA O NUMERO
       Trunc (45.929, 2), -- QUBRA PRA BAIXO
       Mod (10, 2) AS RESTO_DIVISAO,  -- RESTO DA DIVISAÃO
       Trunc(1.99),
       Trunc(1.99, 2)
FROM DUAL;



SELECT * TCONTRATO;

-- FUNÇÕES DA DATA/HORA
SELECT DATA, SYSDATE, DATA + 5 FROM TCONTRATO;

SELECT SYSDATE - DATA AS DIF_DIAS FROM TCONTRATO;

SELECT Trunc (SYSDATE - DATA) AS DIAS FROM TCONTRATO;

SELECT SYSDATE + 2 / 23 AS ADD_HORAS FROM TCONTRATO;

SELECT SYSDATE + 15 / 1440 AS ADD_MINUTOS FROM TCONTRATO;

SELECT SYSDATE + 30 / (3600 * 24) AS ADD_SEGUNDOS FROM TCONTRATO;;



--- FORMATAÇÃO DE DATA

-- CONVERSOR TO_CHAR (DATA, FORMATO)

SELECT SYSDATE, TO CHAR (SYSDATE, 'DD') FROM DUAL;

SELECT TO CHAR (SYSDATE, 'DD/MM/YYYY')  DATA FROM DUAL;

SELECT TO CHAR (SYSDATE 'DD') DIA FROM DUAL;

SELECT TO CHAR (SYSDATE 'MM') MES FROM DUAL;

SELECT TO CHAR ( SYSDATE 'YYYY') ANO FROM DUAL;

SELECT TO CHAR (SYSDATE, 'YY') ANO FROM DUAL;


-------nvl e nvl2-------
SELECT * FROM TCONTRATO;

SELECT Total,
       Desconto,
       Desconto+TOTAL,
       Nvl(Desconto,0),
       Nvl(Desconto,0) + TOTAL,
       Nvl2 (Desconto, TOTAL, -1)
FROM TCONTRATO;

UPDATE TALUNO SET
NOME = NULL
WHERE CD_ALUNO = 44;

---------- CAPITULO 5 ---------

SELECT * FROM TALUNO;


-- PRODUTO CARTESIANO -> ERRADO
SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO


-- CORRETO
SELECT TALUNO.COD_ALUNO, TALUNO.NOME, TCONTRATO.TOTAL
FROM TALUNO, TCONTRATO
WHERE TALUNO.COD_ALUNO = TCONTRATO.COD_ALUNO  -- CRITÉRIO DE UNIÃO.


UPDATE TALUNO SET
NOME = 'MARCOS'
WHERE COD_ALUNO = 5


-- UNIAO DA TABELA DE ALUNO COM CONTRATO

SELECT ALU.COD_ALUNO, ALU.NOME AS ALUNO,
     CON.COD_CONTRATO, CON.DATA, CON.TOTAL

FROM TALUNO ALU, TCONTRATO CON

WHERE CON.COD_ALUNO = ALU.COD_ALUNO   --CRITERIO UNIAO

AND Upper (ALU.NOME) LIKE '%'  -- FILTRO

ORDER BY ALU.NOME -- ORDENAR POR NOME

-------------

SELECT * FROM TITEM
SEKECT * FROM TALUNO
SELECT * FROM TCONTRATO
SELECT * FROM TCURSO


SELECT ALU.COD_ALUNO, ALU.NOME AS ALUNO,
       CON.COD_CONTRATO, CON.DATA, CON.TOTAL,
       ITE.COD_CURSO, CUR.NOME AS CURSO,
       ITE.VALOR

FROM TALUNO ALU, TCONTRATO CON,
     TITEM ITE, TCUR

